/*
Polynomial.js v1.4.5 13/12/2017

Copyright (c) 2017, Robert Eisele (robert@xarg.org)
Dual licensed under the MIT or GPL Version 2 licenses.
*/
(function(x){function B(a){return function(){var c=this.coeff,d=[];for(e in c)d.push(+e);if(0===d.length)return"0";d.sort(function(m,n){return m-n});for(var b="",f=d.length;f--;){var e=d[f];var k=c[e],g=k;if(null!==g&&void 0!==g)if(p&&g instanceof p){if(0!==g.re){""!==b&&0<g.re&&(b+="+");if(-1===g.re&&0!==e)b+="-";else if(1!==g.re||0===e)b+=g.re;1===e?b+="x":0!==e&&(b+="x^"+e)}0!==g.im&&(""!==b&&0<g.im&&(b+="+"),-1===g.im?b+="-":1!==g.im&&(b+=g.im),b+="i",1===e?b+="x":0!==e&&(b+="x^"+e))}else if(g=
g.valueOf(),0!==g){""!==b&&0<g&&(b+="+");if(-1===g&&0!==e)b+="-";else if(1!==g||0===e)b+=k[a]?k[a]():k.toString();1===e?b+="x":0!==e&&(b+="x^"+e)}}return""===b?k[a]?k[a]():k.toString():b}}function q(a){var c={};if(null===a||void 0===a)a=0;switch(typeof a){case "object":a.coeff&&(a=a.coeff);if(u&&a instanceof u||p&&a instanceof p||v&&a instanceof v)c[0]=a;else for(var d in a)l.empty(a[d])||(c[d]=l.parse(a[d]));return c;case "number":return{0:l.parse(a)};case "string":for(;null!==(d=F.exec(a));){var b=
1,f=1;void 0!==d[4]?(b=d[4],f=0):void 0!==d[2]&&(b=d[2]);var e=d[1];b=String(b).match(/[^*/]+|[*/]/g);e=l.parse(e+b[0]);for(var k=1;k<b.length;k+=2)"*"===b[k]?e=l.mul(e,l.parse(b[k+1]||1)):"/"===b[k]&&(e=l.div(e,l.parse(b[k+1]||1)));b=e;void 0!==d[3]&&(f=parseInt(d[3],10));c[f]=void 0===c[f]?b:l.add(c[f],b)}return c}throw"Invalid Param";}function A(a,c){for(var d={},b=t(a),f=t(c),e=[];b>=f;){var k=d[b-f]=l.div(a[b]||0,c[f]||0),g;for(g in c)a[+g+b-f]=l.sub(a[+g+b-f]||0,l.mul(c[g]||0,k));if(null!==
h.trace){var m={};for(g in c)m[+g+b-f]=l.mul(c[g]||0,k);e.push(new h(m))}b=t(a)}null!==h.trace&&(e.push(new h(a)),h.trace=e);return d}function C(a,c){var d=1;for(c=a-c;c<a;a--)d*=a;return d}function h(a){if(!(this instanceof h))return new h(a);this.coeff=q(a)}function w(a){var c={},d;for(d in a)c[d]=a[d];return c}function D(a,c){var d={},b;for(b in a)d[b]=1;for(b in c)d[b]=1;return d}function t(a){var c=-Infinity,d;for(d in a)l.empty(a[d])||(c=Math.max(d,c));return c}function y(a){var c=null,d;for(d in a)!l.empty(a[d])&&
(null===c||+c<+d)&&(c=d);return c}function E(a,c){if(null!==c)for(var d in a)a[d]=l.div(a[d],a[c]);return a}var l={add:function(a,c){return a+c},sub:function(a,c){return a-c},mul:function(a,c){return a*c},div:function(a,c){if(0===c)throw"DIV/0";return a/c},parse:function(a){return parseFloat(a)},empty:function(a){return!a},pow:function(a,c){return Math.pow(a,c)},equals:function(a,c){return a===c}},G=l,F=/([+-]?)(?:([^+x-]+)?(?:x(?:\^([\d\/]+))?)|([^+x-]+))/g;h.trace=null;h.prototype.coeff={};h.prototype.gcd=
function(a){var c=w(this.coeff);for(a=q(a);!(0>t(a));){var d=w(c);A(d,a);c=a;a=d}a=y(c);return new h(E(c,a))};h.prototype.neg=function(){var a={},c=this.coeff,d;for(d in c)a[d]=l.mul(c[d],-1);return new h(a)};h.prototype.reciprocal=function(){var a={},c=this.coeff,d=t(c),b;for(b in c)a[d-b]=c[b];return new h(a)};h.prototype.eval=function(a){var c=this.coeff,d=t(c);if(0>d)return 0;var b=c[d];for(--d;0<=d;d--)b=l.mul(b,a),l.empty(c[d])||(b=l.add(b,c[d]));return b};h.prototype.lc=function(){var a=y(this.coeff);
return this.coeff[a]};h.prototype.lm=function(){var a=y(this.coeff),c={};c[a]=this.coeff[a];return new h(c)};h.prototype.monic=function(){return new h(E(w(this.coeff),y(this.coeff)))};h.prototype.add=function(a){a=q(a);var c={},d=this.coeff,b=D(a,d),f;for(f in b)c[f]=l.add(d[f]||0,a[f]||0);return new h(c)};h.prototype.sub=function(a){a=q(a);var c={},d=this.coeff,b=D(a,d),f;for(f in b)c[f]=l.sub(d[f]||0,a[f]||0);return new h(c)};h.prototype.mul=function(a){a=q(a);var c={},d=this.coeff;for(b in a){var b=
+b;for(var f in d)f=+f,c[b+f]=l.add(c[b+f]||0,l.mul(a[b]||0,d[f]||0))}return new h(c)};h.prototype.addmul=function(a,c){var d=q(a),b=q(c),f={};for(e in d){var e=+e;for(var k in b)k=+k,f[e+k]=l.add(f[e+k]||0,l.mul(d[e]||0,b[k]||0))}return this.add(f)};h.prototype.div=function(a){return new h(A(w(this.coeff),q(a)))};h.prototype.pow=function(a){if(isNaN(a)||0>a||a%1)throw"Invalid";for(var c=new h(1),d=this;0<a;)a&1&&(c=c.mul(d)),d=d.mul(d),a>>=1;return c};h.prototype.mod=function(a){var c=w(this.coeff);
A(c,q(a));return new h(c)};h.prototype.derive=function(a){if(void 0===a)a=1;else if(0>a)return null;var c=this.coeff,d={},b;for(b in c)+b>=a&&(d[b-a]=l.mul(c[b]||0,C(+b,a)));return new h(d)};h.prototype.integrate=function(a){if(void 0===a)a=1;else if(0>a)return null;var c=this.coeff,d={},b;for(b in c)d[+b+a]=l.div(c[b]||0,C(+b+a,a));return new h(d)};h.prototype.result=h.prototype.eval;h.fromRoots=function(a){function c(g){switch(g.length){case 0:return f;case 1:return new h([l.mul(g[0],-1),1]);default:var m=
Math.floor(g.length/2),n=g.slice(m,g.length);return c(g.slice(0,m)).a(c(n))}}var d=a.length,b=l.parse(0);a=a.filter(function(g){return!l.equals(g,b)});d-=a.length;var f=new h(l.parse(1));a=c(a).coeff;var e={},k;for(k in a)e[d+parseInt(k,10)]=a[k];return new h(e)};h.prototype.toString=B("toString");h.prototype.toLatex=B("toLatex");h.prototype.toHorner=function(){function a(e,k){var g="";p&&e instanceof p?0===e.im?(0<e.re&&k&&(g+="+"),g+=e.re):0===e.re?(-1===e.im?g+="-":1!==e.im?(0<e.im&&k&&(g+="+"),
g+=e.im):0<e.im&&k&&(g+="+"),g+="i"):(k&&(g+="+"),g=g+"("+e.toString(),g+=")"):(0<e&&k&&(g+="+"),g+=e.toString());return g}function c(e,k){var g=e.length-k-1,m=e[g]-(e[g-1]||0),n="",r="";0<m&&(n="x",1<m&&(n+="^"+m));0<g&&(n+=a(d[e[g-1]],!0));if(0===k)return a(d[e[g]],!1)+n;0<=g&&e[g]&&(r+="(");r+=c(e,k-1);0<=g&&e[g]&&(r+=")");return r+n}var d=this.coeff,b=[],f;for(f in d)l.empty(d[f])||b.push(+f);if(0===b.length)return"0";b.sort(function(e,k){return e-k});return c(b,b.length-1)};h.prototype.clone=
function(){return new h(this)};h.prototype.degree=function(){return t(this.coeff)};h.setField=function(a){var c={Q:u,C:p,H:v}[a];if(void 0!==c)l={add:function(b,f){return(new c(b)).add(f)},sub:function(b,f){return(new c(b)).sub(f)},mul:function(b,f){return(new c(b)).mul(f)},div:function(b,f){return(new c(b)).div(f)},parse:function(b){return new c(b)},empty:function(b){return(new c(b)).equals(0)},pow:function(b,f){return(new c(b)).pow(f)},equals:function(b,f){return(new c(b)).equals(f)}};else if(!a||
"R"===a)l=G;else if("object"===typeof a)l=a;else if("Z"===a.charAt(0)){var d=+a.slice(1);l={add:function(b,f){return((b+f)%d+d)%d},sub:function(b,f){return((b-f)%d+d)%d},mul:function(b,f){return(b*f%d+d)%d},div:function(b,f){var e=f;for(var k=d,g=0,m=1,n=1,r=0;0!==e;){var z=k/e|0,H=k%e,I=g-n*z;z=m-r*z;k=e;e=H;g=n;m=r;n=I;r=z}e=[k,g,m];if(1!==e[0])throw"DIV/-";return(b*e[1]%d+d)%d},parse:function(b){return parseInt(b,10)},empty:function(b){return void 0===b||0===b},pow:function(b,f){for(var e=1;0<
f;b=(b*b%d+d)%d,f>>=1)f&1&&(e=(e*b%d+d)%d);return e},equals:function(b,f){return b==f}}}};if("function"===typeof define&&define.amd)define(["fraction.js","complex.js","quaternion"],function(a,c,d){u=a;p=c;v=d;return h});else if("object"===typeof exports){var u=require("fraction.js");var p=require("complex.js");var v=require("quaternion");Object.defineProperty(exports,"__esModule",{value:!0});h["default"]=h;h.Polynomial=h;module.exports=h}else u=x.Fraction,p=x.Complex,v=x.Quaternion,x.Polynomial=h})(this);
