/*
 * zzllrr Mather
 * zzllrr@gmail
 * Released under MIT License
 */

technology['Software/AI']=Table([i18(ZLR('Name Type Summary'))],[

	[href(Hs+'generated.photos','Generated Photos'),'Image zip','Free resource of 100k diverse faces generated by AI '+href(Hs+'drive.google.com/drive/folders/1ohmP-2uC0xRHiumkmMEPPRNP_Xqn1H-h','on Google Drive')],
	[href(Hs+'www.thiswaifudoesnotexist.net','This Waifu Does Not Exist - TWDNE'),'JPG','anime faces generated by StyleGAN neural networks and text snippets generated by GPT-2-small'],
	[href(Hs+'thispersondoesnotexist.com','This Person Does Not Exist'),'JPG + TXT','A.I. Generated Faces and Scenes '+
		hrefA('thispersondoesnotexist.com',ZLR('Image Friends Office')).join(' ')+' '+
		hrefA('this@@doesnotexist.com',ZLR('Cat Article')).join(' ')],

],'TBrc');

