/*
 * zzllrr Mather
 * zzllrr@gmail
 * Released under MIT License
 */

technology['Software/AI']=detail(gM('Theory'),
	'五大学派: 进化学派, 连接学派, 符号学派, 贝叶斯学派, 类推学派')+

Table([i18(ZLR('Name Type Summary'))],[

	[href(Hs+'generated.photos','Generated Photos'),'Image zip','Free resource of 100k diverse faces generated by AI '+href(Hs+'drive.google.com/drive/folders/1ohmP-2uC0xRHiumkmMEPPRNP_Xqn1H-h','on Google Drive')],
	[href(Hs+'www.thiswaifudoesnotexist.net','This Waifu Does Not Exist - TWDNE'),'JPG','anime faces generated by StyleGAN neural networks and text snippets generated by GPT-2-small'],
	[href(Hs+'thispersondoesnotexist.com','This Person Does Not Exist'),'JPG + TXT','A.I. Generated Faces and Scenes '+
		hrefA('thispersondoesnotexist.com',ZLR('Image Friends Office')).join(' ')+' '+
		hrefA('this@@doesnotexist.com',ZLR('Cat Article')).join(' ')],
	[href(git('deepfakes/faceswap'),'Deepfakes FaceSwap'),'Python',' utilizes deep learning to recognize and swap faces in pictures and videos'],

	[href('ml5js.org','ml5.js'),'JS','A neighborly approach to creating and exploring artificial intelligence in the browser. '+github('ml5js/ml5-library')+github('ml5js.github.io/ml5-examples/public/')],
	
],'TBrc');

