/*
 * zzllrr Mather
 * zzllrr@gmail
 * Released under MIT License
 */

culture['Quotes']=Table([i18(ZLR('Author Content'))],[



	["Louis L'Amour","Knowledge is like money: to be of value it must circulate, and in circulating it can increase in quantity and, hopefully, in value."],
	['A.N. Wilson',"The fact that logic cannot satisfy us awakens an almost insatiable hunger for the irrational."],
	['A.S. Besicovitch',"A mathematician's reputation rests on the number of bad proofs he has given."],
	['Abe Shenitzer',"One can invent mathematics without knowing much of its history. One can use mathematics without knowing much, if any, of its history. But one cannot have a mature appreciation of mathematics without a substantial knowledge of its history."],
	['Abraham Lincoln',"The probability that we may fail in the struggle ought not to deter us from the support of a cause we believe to be just."],
	['Adrian Mathesis',"All great theorems were discovered after midnight."],
	['Albert Einstein',"Any fool can know. The point is to understand."],
	['Albert Einstein',"Do not worry too much about your difficulties in mathematics, I can assure you that mine are still greater."],
	['Albert Einstein',"God does not play dice with the cosmos."],
	['Albert Einstein',"I have no particular talent. I am only inquisitive."],
	['Albert Einstein',"Imagination is more important than knowledge."],
	['Albert Einstein',"In the beginning (if there was such a thing), God created Newton’s laws of motion together with the necessary masses and forces. This is all; everything beyond this follows from the development of appropriate mathematics methods by means of deduction."],
	['Albert Einstein',"It is the supreme art of the teacher to awaken joy in creative expression and knowledge."],
	['Albert Einstein',"Not everything that counts can be counted. Not everything that can be counted counts."],
	['Albert Einstein',"Only two things are infinite, the universe and human stupidity, and I'm not sure about the former."],
	['Albert Einstein',"Pure mathematics is, in its way, the poetry of logical ideas."],
	['Albert Einstein',"Science without religion is lame; religion without science is blind."],
	['Albert Einstein',"Since the mathematicians have invaded the theory of relativity, I do not understand it myself any more."],
	['Albert Einstein',"The most beautiful thing we can experience is the mysterious. It is the source of all true art and science."],
	['Albert Einstein',"When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity."],
	['Albert Einstein','It is a miracle that curiosity survives formal education.'],
	['Albert Einstein',"As far as the laws of mathematics refer to reality, they are not certain, and as far as they are certain, they do not refer to reality."],
	['Albrecht Durer',"Geometry is the foundation of all painting."],
	['Aleister Crowley',"I was asked to memorise what I did not understand; and, my memory being so good, it refused to be insulted in that manner."],
	['Alexandre Dumas',"How is it that little children are so intelligent and men so stupid? It must be education that does it."],
	['Alexandre Dumas',"One's work may be finished some day, but one's education never."],
	['Alfred North Whitehead',"From the very beginning of his education, the child should experience the joy of discovery."],
	['Alfred North Whitehead',"The science of Pure Mathematics, in its modern developments, may claim to be the most original creation of the human spirit."],
	['Alfred North Whitehead',"We think in generalities, but we live in details."],
	['Alvin Toffler',"The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn."],
	['André Gide',"The want of logic annoys. Too much logic bores. Life eludes logic, and everything that logic alone constructs remains artificial and forced."],
	['Andy Warhol',"Making money is art and working is art and good business is the best art."],
	['Ani DiFranco','When I was four years old they tried to test my IQ. They showed me a picture of three oranges and a pear. They asked me."which one is different and does not belong?" They taught me different was wrong.'],
	['Anonymous',"Today is the tomorrow we worried about yesterday."],
	['Antisthenes',"The most useful piece of learning for the uses of life is to unlearn what is untrue."],
	['Archimedes',"I am persuaded that this method [for calculating the volume of a sphere] will be of no little service to mathematics. For I foresee that once it is understood and established, it will be used to discover other theorems which have not yet occurred to me, by other mathematicians, now living or yet unborn."],
	['Aristotle',"It is the mark of an educated mind to be able to entertain a thought without accepting it."],
	['Aristotle',"The mathematical sciences particularly exhibit order, symmetry, and limitations; and these are the greatest forms of the beautiful."],
	['B.F. Skinner',"Education is what survives when what has been learned has been forgotten."],

	['Barbie Dol',"Math class is tough."],
	['Ben Franklin',"Well done is better than well said."],
	['Benjamin Disraeli',"There are three kinds of lies: lies, damned lies, and statistics."],
	['Benjamin Franklin',"What science can there be more noble, more excellent, more useful for men, more admirably high and demonstrative, than this of mathematics?"],
	['Bernard Baruch',"Millions saw the apple fall, but Newton asked why."],
	['Bernard Baruch','Millions saw the apple fall, but Newton asked why.'],
	['Bertrand Russell',"Mathematics, rightly viewed, possesses not only truth, but supreme beauty."],
	['Bertrand Russell',"Thus mathematics may be defined as the subject in which we never know what we are talking about, nor whether what we are saying is true."],
	['Bill Cosby',"A word to the wise ain't necessary -- it's the stupid ones that need our advice."],
	['Bjarne Stroustrup',"I have always wished that my computer would be as easy to use as my telephone. My wish has come true ... I no longer know how to use my telephone."],
	['Black Elk',"Everything tries to be round."],
	['Bob Guiccione, Jr.',"Education is learning more than is being taught. It's the chemistry of curiosity exposed to information. In that sense all of life is potentially school. And even I can pass that."],
	['Boris Pasternak',"What is laid down, ordered, factual, is never enough to embrace the whole truth: life always spills over the rim of every cup."],
	['Brahmagupta',"A person who can, within a year, solve x² - 92y² = 1 is a mathematician."],
	['Carl Friedrich Gauss',"Mathematics is the Queen of the Sciences and number theory the queen of mathematics."],
	['Carl Jacobi',"One should always generalize."],
	['Charles Lamb',"Nothing puzzles me more than the time and space; and yet nothing troubles me less."],
	['Charles R Darwin',"A mathematician is a blind man in a dark room looking for a black cat which isn't there."],
	['Charlie Hoff',"Getting a good education for your child is not a spectator sport."],
	['Chinese Proverb',"Men who say it cannot be done should not interrupt those who are doing it."],
	['Chinese Proverb',"I hear and I forget. I see and I remember. I do and I understand."],
	['Claude Bragdon',"Mathematics is the handwriting on the human consciousness of the very Spirit of Life itself."],
	['Cokie Roberts',"As long as algebra is taught in school, there will be prayer in school."],
	['Confucius',"Everything has beauty, but not everyone sees it."],
	['Confucius',"He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever."],
	['Confucius',"Learning without thought is labor lost; thought without learning is perilous."],
	['David Hilbert',"Mathematics is a game played according to certain simple rules with meaningless marks on paper."],
	['David Hilbert',"The infinite! No other question has ever moved so profoundly the spirit of man."],
	['David Hilbert',"Before beginning [to try to prove Fermat's Last Theorem] I should have to put in three years of intensive study, and I haven't that much time to squander on a probable failure."],
	['David L. Finn',"The journey for an education starts with a childhood question."],
	['Demergue',"Some people study all their life, and at their death have learned everything but to think."],
	['Descartes',"Cogito, Ergo Sum. I think, therefore I am."],
	['Descartes',"Perfect numbers like perfect men are very rare."],
	['Descartes',"The reading of all good books is like a conversation with the finest people of past centuries."],
	['Donald Knuth',"Science is what we understand well enough to explain to a computer. Art is everything else we do."],
	['Doug Larson',"Home computers are being called upon to perform many new functions, including the consumption of homework formerly eaten by the dog."],
	['Dr. Carl E. Linderholm',"A diagram is worth a thousand words."],
	['Dr. Seuss',"Think! Think and wonder. Wonder and think. How much water can 55 elephants drink?"],
	['E. Kim Nebeuts',"To state a theorem and then to show examples of it is literally to teach backwards."],
	['E.M. Forster',"I suggest that the only books that influence us are those for which we are ready, and which have gone a little farther down our particular path than we have yet got ourselves."],
	['E.T. Bell',"Obvious is the most dangerous word in mathematics."],

	['Ecclesiastes',"I returned, and saw under the sun, that the race is not to the swift, nor the battle to the strong, neither yet bread to the wise, nor yet riches to men of understanding, nor yet favor to men of skill; but time and chance happeneth to them all."],
	['Edward Kasner and James Newman',"The infinite in mathematics is always unruly unless it is properly treated."],
	['Edward Kasner and James R. Newman',"Mathematics is the science which uses easy words for hard ideas."],
	['Erasmus',"When I get a little money, I buy books and if any is left, I buy food and clothes."],
	['Erma Bombeck',"When my kids become wild and unruly, I use a nice, safe playpen. When they're finished, I climb out."],
	['Euclid',"There is no Royal Road to Geometry."],
	['Euripides',"Mighty is geometry; joined with art, resistless."],

	['Francios Voltaire',"There is an astonishing imagination even in the science of mathematics...We repeat, there is far more imagination in the head of Archimedes than in that of Homer."],
	['Francis Bacon',"A man whose mind has gone astray should study mathematics."],
	['Francis Bacon',"Histories make men wise; poets witty; the mathematics, subtile; natural philosophy, deep; moral, grave; logic and rhetoric, able to contend."],
	['Francis Bacon',"If a man will begin with certainties, he shall end in doubts; but if he will be content to begin with doubts, he shall end in certainties."],
	['Francis Bacon',"Some books are to be tasted, others to be swallowed, and some few to be chewed and digested."],
	['Francois le Lionnais',"Who has not been amazed to learn that the function y = e^x, like a phoenix rising from its own ashes, is its own derivative?"],
	['Frank Kingdon',"Questions are creative acts of intelligence."],
	['Freeman Dyson',"One factor that has remained constant through all the twists and turns of the history of physical science is the decisive importance of the mathematical imagination."],
	['Friedrich Nietzsche',"Ah, women. They make the highs higher and the lows more frequent."],
	['Fyodor Mikhailovich Dostoyevsky',"Man has such a predilection for systems and abstract deductions that he is ready to distort the truth intentionally, he is ready to deny the evidence of his senses only to justify his logic."],
	['G.H. Hardy',"A mathematician, like a painter or poet, is a maker of patterns. If his patterns are more permanent than theirs, it is because they are made with ideas."],
	['G.H. Hardy',"The mathematician's patterns, like the painter's or poet's, must be beautiful. The ideas, like the colours or the words, must fit together in a harmonious way. Beauty is the first test: There is no permanent place in the world for ugly mathematics."],
	['G.K. Chesterton',"A great curse has fallen upon modern life with the discovery of the vastness of the word Education."],
	['G.K. Chesterton',"A queer and almost mad notion seems to have got into the modern head that, if you mix up everybody and everything more or less anyhow, the mixture may be called unity, and the unity may be called peace. It is supposed that, if you break down all doors and walls so that there is no domesticity, there will then be nothing but friendship. Surely somebody must have noticed by this time that the men living in a hotel quarrel at least as often as the men living in a street."],
	['G.K. Chesterton',"All science, even the divine science, is a sublime detective story. Only it is not set to detect why a man is dead; but the darker secret of why he is alive."],
	['G.K. Chesterton',"Art, like morality, consists of drawing the line somewhere."],
	['G.K. Chesterton',"I do not believe in a fate that falls on men however they act; but I do believe in a fate that falls on them unless they act."],
	['G.K. Chesterton',"Men do not differ much about what things they will call evils; they differ enormously about what evils they will call excusable."],
	['G.K. Chesterton',"The simplification of anything is always sensational."],
	['G.K. Chesterton',"There are some desires that are not desirable."],
	['G.K. Chesterton',"There are two kinds of paradoxes. They are not so much the good and the bad, nor even the true and the false. Rather they are the fruitful and the barren; the paradoxes which produce life and the paradoxes that merely announce death. Nearly all modern paradoxes merely announce death."],
	['G.K. Chesterton',"You can't have the family farm without the family."],
	['G.M. Trevelyan',"Education... has produced a vast population able to read but unable to distinguish what is worth reading."],
	['Galilei Galileo',"The Universe is a grand book which cannot be read until one first learns to comprehend the language and become familiar with the characters in which it is composed. It is written in the language of mathematics…"],
	['Galileo Galilei',"[Paradoxes of the infinite arise] only when we attempt, with our finite minds, to discuss the infinite, assigning to it those properties which we give to the finite and limited;"],
	['Galileo',"God wrote the universe in the language of mathematics."],
	['Galileo',"Nature's great book is written in mathematics."],
	['Georg Cantor',"The essence of mathematics is in its freedom."],
	['George Bernard Shaw',"If you hold yourself up to your children, hold yourself up as an object lesson and not as an example."],
	['George Cantor','In mathematics the art of proposing a question must be held of higher value than solving it.'],
	['George Escher',"Father [M.C. Escher] had difficulty comprehending that the working of his mind was akin to that of a mathematician. He greatly enjoyed the interest in his work by mathematicians and scientists, .."],
	['George Orwell'," Advertising is the rattling of a stick inside a swill bucket."],
	['George Orwell'," At age 50, every man has the face he deserves."],
	['George Polya',"A GREAT discovery solves a great problem but there is a grain of discovery in any problem."],
	['George Polya',"A mathematician who can only generalise is like a monkey who can only climb up a tree, and a mathematician who can only specialise is like a monkey who can only climb down a tree. In fact neither the up monkey nor the down monkey is a viable creature. A real monkey must find food and escape his enemies and so must be able to incessantly climb up and down. A real mathematician must be able to generalise and specialise."],
	['George Polya',"A mathematics teacher is a midwife to ideas."],
	['George Polya',"Beauty in mathematics is seeing the truth without effort."],
	['George Polya',"Geometry is the science of correct reasoning on incorrect figures."],
	['George Polya',"I am too good for philosophy and not good enough for physics. Mathematics is in between."],
	['George Polya',"If there is a problem you can't solve, then there is an easier problem you can't solve: find it."],
	['George Polya',"My method to overcome a difficulty is to go round it."],
	['George Polya',"The first rule of discovery is to have brains and good luck.  The second rule of discovery is to sit tight and wait till you get a bright idea."],
	['George Polya',"There are many questions which fools can ask that wise men cannot answer."],
	['George Polya',"When introduced at the wrong time or place, good logic may be the worst enemy of good teaching."],
	['George Polya','Beauty in mathematics is seeing the truth without effort.'],
	['George Santayana',"The great difficulty in education is to get experience out of ideas."],
	['Godfrey Harold Hardy',"Beauty is the first test: there is no permanent place in the world for ugly mathematics."],
	['Gustave Flaubert',"Poetry is as exact a science as geometry."],
	['H. F. Feh',"Mathematics serves as a handmaiden for the explanation of the quantitative situations in other subjects, such as economics, physics, navigation, finance, biology and even the arts."],
	['H.G. Wells',"You have learned something.  That always feels at first as if you had lost something."],
	['H.L. Mencken"',"For every complex problem, there is a solution that is simple, neat, and wrong."],
	['Harish Chandra',"I have often pondered over the roles of knowledge or experience, on the one hand, and imagination or intuition, on the other, in the process of discovery. I believe that there is a certain fundamental conflict between the two, and knowledge, by advocating caution, tends to inhibit the flight of imagination. Therefore, a certain naivete, unburdened by conventional wisdom, can sometimes be a positive asset."],
	['Henri Poincare',"The mathematician does not study pure mathematics because it is useful; he studies it because he delights in it and he delights in it because it is beautiful."],
	['Henri Poincare',"There are no solved problems; there are only problems that are more or less solved."],
	['Henry Brooks Adams',"A teacher affects eternity; he can never tell where his influence stops."],
	['Henry Clay',"Statistics are no substitute for judgment."],
	['Henry David Thoreau',"What does education often do?  It makes a straight-cut ditch of a free, meandering brook."],
	['Henry Ford',"Failure is the opportunity to begin again, more intelligently."],
	['Henry L. Doherty',"Get over the idea that only children should spend their time in study.  Be a student so long as you still have something to learn, and this will mean all your life."],
	['Henry Miller',"The real leader has no need to lead, he is content to point the way."],
	['Heraclitus',"Much learning does not teach understanding."],
	['Herman Henkel',"In most sciences one generation tears down what another has built and what one has established another undoes. In mathematics alone each generation adds a new story to the old structure."],
	['Hermann Weyl',"Symmetry, as wide or as narrow as you define its meaning, is one idea by which man through the ages has tried to comprehend and create order, beauty and perfection."],
	['Hermite',"I turn away with fear and horror from this lamentable plague of functions which do not have derivatives."],
	['I.N. Herstein',"The value of a problem is not so much coming up with the answer as in the ideas and attempted ideas it forces on the would be solver."],
	['Ice T',"I write rhymes with addition and algebra, mental geometry."],
	['Isaac Asimov',"After years of finding mathematics easy, I finally reached integral calculus and came up against a barrier.  I realized that this was as far as I could go, and to do this day I have never successfully gone beyond it in any but the most superficial way."],
	['Isaac Newton',"If I have seen farther than other men, it is because I have stood on the shoulders of giants."],
	['J.B.S. Haldane',"Now my own suspicion is that the Universe is not only queerer than we suppose, but queerer than we can suppose."],
	['J.M. Barrie',"We are all failures--at least, all the best of us are."],
	['Jaime Escalante',"I do not believe in the gifted. If [the students] have ganas[Spanish for desire], I can make them do it."],
	['James Goldsmith',"If you pay peanuts, you get monkeys."],
	['James Hopwood Jeans',"From the intrinsic evidence of his creation, the Great Architect of the Universe now begins to appear as a pure mathematician."],
	['James Pierpont',"The notion of infinity is our greatest friend; it is also the greatest enemy of our peace of mind."],
	['James Russell Lowell',"Books are the bees which carry the quickening pollen from one to another mind."],
	['Jason Kidd',"We're going to turn this team around 360 degrees."],
	['Jassamyn West',"Teaching is the royal road to learning."],
	['Jeff Pesis',"Hardware -- the parts of a computer that can be kicked."],
	['Jeffrey Archer',"I was allowed to ring the bell for five minutes until everyone was in assembly. It was the beginning of power."],
	['Joel Franklin',"We will prove this by the method of prolonged staring."],
	['Johann von Neumann',"In mathematics, you don't understand things. You just get used to them."],
	['Johannes Kepler',"Where there is matter, there is geometry."],
	['John Adams',"I must study politics and war that my sons may have liberty to study mathematics and philosophy."],
	['John Allen Paulos',"Mathematics is no more computation than typing is literature."],
	['John Arbuthnot',"Mathematical knowledge adds vigor to the mind, frees it from prejudice, credulity, and superstition."],
	['John Dewey',"A problem well stated is half-solved."],
	['John F. Kennedy',"The problems of the world cannot possibly be solved by skeptics or cynics whose horizons are limited by the obvious realities. We need men who can dream of things that never were."],
	['John Galsworthy',"Idealism increases in direct proportion to one's distance from the problem."],
	['John Henry Newman',"A great memory does not make a mind, any more than a dictionary is a piece of literature."],
	['John Locke',"Logic is the anatomy of thought."],
	['John Locke',"The only fence against the world is a thorough knowledge of it."],
	['John Michel',"The mathematical rules of the universe are visible to men in the form of beauty."],
	['John von Neumann',"Truth is much too complicated to allow anything but approximations."],
	['Joseph Fourier',"Mathematics compares the most diverse phenomena and discovers the secret analogies that unite them."],
	['K. Dewdney',"The most powerful single idea in mathematics is the notion of a variable."],
	['Kasner and Newman',"Perhaps the greatest paradox of all is that there are paradoxes in mathematics."],
	['Kelley',"A topologist is a man who doesn't know the difference between a coffee cup and a doughnut."],
	['Kenyan proverb',"The world is not given to you by your parents. It is loaned to you by your children."],
	['Lebegue',"The only teaching that a professor can give, in my opinion, is that of thinking in front of his students."],
	['Lee Iacocca',"In a completely rational society, the best of us would be teachers and the rest of us would have to settle for something less, because passing civilization along from one generation to the next ought to be the highest honor and the highest responsibility anyone could have."],
	['Gosta Mittag Leffler',"The mathematician's best work is art, a high perfect art, as daring as the most secret dreams of imagination, clear and limpid. Mathematical genius and artistic genius touch one another."],
	['Leibniz',"Music is the pleasure the human mind experiences from counting without being aware that it is counting."],
	['Leonardo Da Vinci',"The merit of painting lies in the exactness of reproduction. Painting is a science and all sciences are based on mathematics. No human inquiry can be a science unless it pursues its path through mathematical exposition and demonstration."],
	['Leonardo da Vinci',"Mechanics is the paradise of the mathematical sciences because by means of it one comes to the fruits of mathematics."],
	['Leonhard Euler',"For since the fabric of the universe is most perfect and the work of a most wise Creator, nothing at all takes place in the universe in which some rule of maximum or minimum does not appear."],
	['Leopold Kronecker',"The Good Lord made all the integers; the rest is man's doing."],
	['Leopold Kronecker','God made the integers, all the rest is the work of man'],

	['Linus Pauling',"The best way to have a good idea is to have lots of ideas."],
	['Lloyd Alexander',"We learn more by looking for the answer to a question and not finding it than we do from learning the answer itself."],
	['Louis Pasteur',"Fortune favors the prepared mind."],
	['Louis Pasteur',"Inspiration is the impact of a fact on a well-prepared mind."],
	['Louise Sawyer',"You get what you settle for."],
	['Lynn A. Steen',"Mathematics, in the common lay view, is a static discipline based on formulas...But outside the public view, mathematics continues to grow at a rapid rate...the guide to this growth is not calculation and formulas, but an open ended search for pattern."],
	['Lynn A. Steen',"What humans do with the language of mathematics is to describe patterns.."],
	['M. Mead',"Never doubt that a small group of thoughtful citizens can change the world. Indeed, it is the only thing that ever has."],
	['M.C. Escher',"Science and art sometimes can touch one another, like two pieces of the jigsaw puzzle which is our human life, and that contact may be made across the borderline between the two respective domains."],
	['Mark Twain',"Always tell the truth, that way you won't have to remember what you said."],
	['Mark Twain',"October. This is one of the peculiarly dangerous months to speculate in stocks in. The others are July, January, September, April, November, May, March, June, December, August, and February."],
	['Mark Twain',"We have not the reverent feeling for the rainbow that a savage has, because we know how it is made. We have lost as much as we gained by prying into that matter."],
	['Mark Twain',"When I was a boy of 14, my father was so ignorant I could hardly stand to have the old man around. But when I got to 21, I was astonished at how much the old man had learned in 7 years."],
	['Martha Washington',"The greater part of our happiness or misery depends on our dispositions, and not on our circumstances."],
	['Martin Gardner',"A surprising proportion of mathematicians are accomplished musicians. Is it because music and mathematics share patterns that are beautiful?"],
	['Martin Gardner',"One would be hard put to find a set of whole numbers with a more fascinating history and more elegant properties surrounded by greater depths of mystery--and more totally useless--than the perfect numbers."],
	['Martin Luther King',"Those who love peace must learn to organize as well as those who love war."],
	['Martin Luther',"Medicine makes people ill, mathematics makes them sad, and theology makes them sinful."],
	['Marvin Minsky',"You don't understand anything until you learn it more than one way."],
	['Mary Beth Ruskai',"We cannot hope that many children will learn mathematics unless we find a way to share our enjoyment and show them its beauty as well as its utility."],
	['Mary Kay Ash',"Sandwich every bit of criticism between two thick layers of praise."],
	['Matthew Prior',"Circles to square and cubes to double would give a man excessive trouble."],
	['Mickey Mouse',"Arithmetic is being able to count up to twenty without taking off your shoes."],
	['Mohammed',"The ink of the scholar is more sacred than the blood of the martyr."],
	['Montaigne ',"I do not teach, I relate."],
	['Montesquieu',"I have never known any distress that an hour's reading did not relieve."],
	['Morris Kline',"Actually, most mathematics courses do not teach reasoning of any kind. Students are so baffled by the material that they are obliged to memorize in order to pass examinations."],
	['Morris Kline',"Mathematicians create by acts of insights and intuition.  Logic then sanctions the conquests of intuition."],
	['Nathanael West',"Numbers constitute the only universal language."],
	['Native American saying',"Tell me and I'll forget. Show me and I may not remember. Involve me, and I'll understand."],
	['Nicolai Lobachevsky',"There is no branch of mathematics, however abstract, which may not someday be applied to the phenomena of the real world."],
	['Nolan Bushnell',"The ultimate inspiration is the deadline."],
	['Norman Cousins',"Infinity converts the possible into the inevitable."],
	['Oscar Wilde',"It is better to have a permanent income than to be fascinating."],
	['Oscar Wilde',"Most people die of a sort of creeping common sense, and discover when it is too late that the only things one never regrets are one's mistakes."],
	['P.J. Davis',"One of the endlessly alluring aspects of mathematics is that its thorniest paradoxes have a way of blooming into beautiful theories."],
	['Pappas',"Bees … by virtue of a certain geometrical forethought … know that the hexagon is greater than the square and the triangle, and will hold more honey for the same expenditure of material."],
	['Paul Brodeur',"Statistics are human beings with the tears wiped away."],
	['Paul Erdos',"It will be another million years, at least, before we understand the primes."],
	['Paul Erdös',"I will know I really am in trouble when I forget the name Alzheimer's."],
	['Paul Erdös',"A mathematician is a machine for turning coffee into theorems."],
	['Paul Erdös',"When I was a child, the Earth was said to be two billion years old. Now scientists say it's four and a half billion. So that makes me two and a half billion."],
	['Paul Halmos',"A good stack of examples, as large as possible, is indispensable for a thorough understanding of any concept, and when I want to learn something new, I make it my first job to build one."],
	['Paul Halmos',"It is the duty of all teachers, and of teachers of mathematics in particular, to expose their students to problems much more than to facts."],
	['Paul Halmos',"Mathematics -- this may surprise or shock some -- is never deductive in creation."],
	['Paul Halmos',"Mathematics is not a deductive science – that's a cliché. When you try to prove a theorem, you don't just list the hypotheses, and then start to reason. What you do is trial and error, experimentation, guesswork."],
	['Paul Halmos',"The only way to learn mathematics is to do mathematics. That tenet is the foundation of the do-it-yourself, Socratic, or Texas method, .."],
	['Penelope Fitzgerald',"However, no two people see the external world in exactly the same way. To every separate person a thing is what he thinks it is--in other words, not a thing, but a think."],
	['Peter Marshall',"Small deeds done are better than great deeds planned."],
	['Philippe Shnoebelen',"Algebraic symbols are used when you do not know what you are talking about."],
	['Pierre Boatroux',"Logic is invincible, because in order to combat logic it is necessary to use logic."],
	['Pierre Simon de La Place',"The most important questions in life are, for the most part, really only problems of probability."],
	['Pierre de La Place',"The theory of probabilities is at bottom nothing but common sense reduced to calculus."],
	['Piet Hein',"A bit beyond perception's reach<br>I sometimes believe I see<br>that life is two locked boxes<br>each containing the other's key."],
	['Plato',"God ever geometrizes."],
	['Plato',"He who can properly define and divide is to be considered a god."],
	['Plato',"I have hardly ever known a mathematician who was capable of reasoning."],
	['Plato',"Let early education be a sort of amusement. You will then be better able to find out the natural bent."],
	['Plato',"Numbers are the highest degree of knowledge. It is knowledge itself."],
	['Plato',"The beginning is the most important part of the work."],
	['Plato',"There still remain three studies suitable for free man. Arithmetic is one of them."],
	['Plutarch',"A mind is a fire to be kindled, not a vessel to be filled."],
	['Robert Silensky',"We've all heard that a million monkeys banging on a million typewriters will eventually reproduce the entire works of Shakespeare. Now, thanks to the internet, we know this is not true."],
	['R.W. Hamming',"The purpose of computing is insight, not numbers!."],
	['Rabindranath Tagore',"A mind all logic is like a knife all blade. It makes the hand bleed that uses it."],
	['Reinhold Niebuhr',"God grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference."],
	['Rene Descartes',"Each problem that I solved became a rule which served afterwards to solve other problems."],
	['Rene Descartes',"It is truth very certain that, when it is not in one's power to determine what is true, we ought to follow what is more probable."],
	['Richard Hofstadter',"If there is anything more dangerous to the life of the mind than having no independent commitment to ideas, it is having an excess of commitment to some special and constricting idea."],
	['Robert Frost',"I am not a teacher, I am an awakener."],
	['Robert Frost',"Never ask of money spent<br>Where the spender thinks it went.<br>Nobody was ever meant<br>To remember or invent<br>What he did with every cent. ---"],
	['Robert Louis Stevenson',"Perpetual devotion to what a man calls his business is only to be sustained by perpetual neglect of many other things."],
	['Robertson Davies',"A truly great book should be read in youth, again in maturity and once more in old age, as a fine building should be seen by morning light, at noon and by moonlight."],
	['Roger Bacon',"Mathematics is the gate and key to the sciences."],
	['Rosalind Russell',"Flops are a part of life's menu and I've never been a girl to miss out on any of the courses."],
	['S. Gudder',"The essence of mathematics is not to make simple things complicated, but to make complicated things simple."],
	['S. Wilson',"Only the curious will learn and only the resolute overcome the obstacles to learning. The quest quotient has always excited me more than the intelligence quotient."],
	['Samuel Beckett',"Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better."],
	['Schuller',"What would you dream for if you knew you couldn't fail?"],
	['Scott Adams',"The creator of the universe works in mysterious ways. But he uses a base ten counting system and likes round numbers."],
	['Seneca',"If you would make a man happy, do not add to his possessions but subtract from the sum of his desires."],
	['Shelia Tobias',"There is a difference between not knowing and not knowing yet."],
	['Sir Arthur Conan Doyle',"A man should keep his little brain attic stocked with all the furniture that he is likely to use, and the rest he can put away in the lumber-room of his library, where he can get it if he wants it."],
	['Sir Arthur Conan Doyle',"How often have I said to you that when you have eliminated the impossible, whatever remains, however improbable, must be the truth?"],
	['Sophia Kovalevskaya',"It is impossible to be a mathematician without being a poet in soul"],
	['Sophus Lie',"Among all of the mathematical disciplines the theory of differential equations is the most important... It furnishes the explanation of all those elementary manifestations of nature which involve time."],
	['St. Augustine',"The good Christian should beware of mathematicians and all those who make empty prophecies. The danger already exists that mathematicians have made a covenant with the devil to darken the spirit and confine man in the bonds of Hell."],
	['Stephen Hawking',"God not only plays dice. He also sometimes throws the dice where they cannot be seen."],
	['Steven Wright',"Black holes are where God divided by zero."],
	['Steven Wright',"Five out of four people have trouble with fractions."],
	['Susan Gerhart',"One person's constant is another person's variable."],
	['Sydney J. Harris',"The real danger is not that computers will begin to think like men, but that men will begin to think like computers."],
	['Tallulah Bankhead',"I read Shakespeare and the Bible, and I can shoot dice.  That's what I call a liberal education."],
	['Theodore Roosevelt',"Whenever you are asked if you can do a job, tell 'em, 'Certainly I can!' Then get busy and find out how to do it."],
	['Thomas Carlyle',"I don't pretend to understand the Universe--it's a great deal bigger than I am."],
	['Thomas Edison',"Opportunity is missed by most people because it is dressed in overalls and looks like work."],
	['Thomas Edison',"There ain't no rules around here! We're trying to accomplish something!"],
	['Thomas Mann',"I tell them if they will occupy themselves with the study of mathematics, they will find in it the best remedy against the lusts of the flesh."],
	['Thomas Robert Malthus',"Population, when unchecked, increases in a geometrical ratio. Subsistence increases only in an arithmetical ratio."],
	['Tolstoy',"A man is like a fraction whose numerator is what he is and whose denominator is what he thinks of himself. The larger the denominator, the smaller the fraction."],
	['Tom Lehrer',"But don't panic. Base 8 is just like Base 10 really. If you're missing two fingers."],
	['Tom Lehrer',"But in the new (math) approach, the important thing is to understand what you're doing, rather than to get the right answer."],
	['Ugo Betti',"I think the family is the place where the most ridiculous and least respectable things in the world go on."],
	['Unknown',"Life without geometry is pointless."],
	['Ursula K. Le Guin',"My imagination makes me human and makes me a fool; it gives me all the world and exiles me from it."],
	['Vernon Law',"Experience is the hardest kind of teacher. It gives you the test first, and the lesson afterward."],
	['Voltaire',"The more you know, the less sure you are."],
	['W. Edwards Deming',"Learning is not compulsory... neither is survival."],
	['W. Somerset Maugham',"Imagination grows by exercise and contrary to common belief is more powerful in the mature than in the young."],
	['W.J. Deijmann',"An educated mind is useless without a focused will, and dangerous without a loving heart."],
	['W.S. Gilbert in the Pirates of Penzance',"I'm very good at integral and differential calculus, I know the scientific names of beings animalculous; in short, in matters vegetable, animal, andmineral, I am the very model of the modern Major General."],
	['Walter Savage Landor',"What is reading but silent conversation?"],
	['William Betz',"The symbolism of algebra is its glory. But it also is its curse."],
	['William Hazlitt',"That which any one has been long learning unwillingly, he unlearns with proportional eagerness and haste."],
	['William James',"The union of the mathematician with the poet, fervor with measure, passion with correctness, this surely is the ideal."],
	['Winston Churchill',"We make a living by what we get, but we make a life by what we give."],
	['Woody Allen',"Money is better than poverty, if only for financial reasons."],
	["inscription above Plato's Academy","Let no one ignorant of geometry enter here."],
	['unknown',"Any teacher that can be replaced by a computer should be replaced by a computer."],
	['unknown',"Confidence is not about being always right, but always knowing what to do when things go wrong."],
	['unknown',"If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is."],
	['unknown',"If you want to get something done, find a busy man."],
	['unknown',"Physicists defer only to mathematicians, and mathematicians defer only to God."],
	['unknown','Attitude is more an indicator of success than aptitude.'],

],'TBrc')+detail(gM('Reference'),Table([i18(ZLR('Name Type Author Summary'))],[

	[href(Hs+'www.livingmath.net/quotes','Living Math'),'HTML','Julie Brennan',''],

	
],'TBrc'),1);
